### ISSUE TITLE
Add assets with no POSITION attribute

### ISSUE THREAD

**Issue by bghgary** [KhronosGroup/glTF-Asset-Generator#407]
One can argue this is a negative test, but since https://github.com/KhronosGroup/glTF/issues/1332 is asking for this, we can make an exception similar to the compatibility tests.

**Comment by stevk** [comment]
Are there any other attributes they want included in this model?

**Comment by bghgary** [comment]
I think it's just POSITION. We had assumed that POSITION is always there, but there can be a valid case via an extension where POSITION is missing.
