### ISSUE TITLE
asymmetric, non-zero tangents for cubic spline

### ISSUE THREAD

**Issue by andreasplesch** [KhronosGroup/glTF-Asset-Generator#441]
Currently, all tangents for cubic spline interpolation in animations are zeroes:

https://github.com/bghgary/glTF-Asset-Generator/blob/master/Source/ModelGroups/Animation_Node.cs#L197

Consider using asymmetric tangents for a more demanding test asset. For example, the translation animation could involve the y axis to produce an interesting path.

**Comment by andreasplesch** [comment]
Here is what I get with these 3 tuples of translation as output:

 0 0 0
-0.1 0 0
 0 0 0

 0 5 0 // tangent 5 in y
 0.1 0 0
 0 3 0 // tangent 3 in y

 0 0 0
 -0.1 0
 0 0 0 0

![nonzerotangents](https://user-images.githubusercontent.com/6171115/43467043-da5ad932-94ae-11e8-943d-ca7f3491e07c.gif)

**Comment by bghgary** [comment]
> Consider using asymmetric tangents for a more demanding test asset.

Sounds good. Just out of curiosity, is there a specific situation where this can fall down? I'm trying to decide whether we need two tests or one. Please feel free to open a PR to make the change.

**Comment by andreasplesch** [comment]
See #442 , unfortunately, I do not have a way to test the changes, including if other edits are required as a consequence.

I cannot really think of a situation where asymmetry would be catastrophic. Large tangents can have large effects, obviously, but this would not require an additional test.

**Comment by kcoley** [comment]
Hi @andreasplesch , sorry we missed your PR!  We can make a model to handle this case for the Animation_Node tests.

**Comment by stevk** [comment]
Fixed in PR #477
