### ISSUE TITLE
Adding a new model group often require re-numbering folder index

### ISSUE THREAD

**Issue by bghgary** [KhronosGroup/glTF-Asset-Generator#468]
It is annoying to review PRs that add model groups when the folder index changes because a model group was inserted.

Consider using model group name or some kind of unique id instead of an index in the asset viewer url.

**Comment by bghgary** [comment]
Take this one for example: https://github.com/KhronosGroup/glTF-Asset-Generator/pull/466/files#diff-d6b2c4fb3485dd38db0a4d4a99ac7ee2

**Comment by kcoley** [comment]
Just merged a fix for this: https://github.com/KhronosGroup/glTF-Asset-Generator/pull/484

**Comment by stevk** [comment]
Was a required item for #475
