### ISSUE TITLE
Upgrade to .NET Core 3.1

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF-Asset-Generator#561]
![image](https://user-images.githubusercontent.com/3479527/72884443-90275a00-3d1f-11ea-8b24-6fb9678d8619.png)

https://dotnet.microsoft.com/platform/support/policy/dotnet-core

**Comment by lexaknyazev** [comment]
Besides simply changing `TargetFramework` to `netcoreapp3.1`, several other updates could be done here:

- It should be possible to switch to the [new System.Text.Json APIs](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/).
- It looks like floating number formatting has slightly changed since .NET Core 2.2:
  - Fewer decimal digits are now written for some values. Validation passes anyway.
  - Sign is now written for `-0.0`, see diff for `Output\Positive\Node_Attribute\README.md`

**Comment by lexaknyazev** [comment]
@bghgary  What do you think about retargeting this project? .NET Core 2.2 reached its EoL about a year ago.

Given that glTF-Asset-Generator is an app rather than a library, we could aim as high as `net5.0`.

**Comment by bghgary** [comment]
Sure, I don't see any issues with that.

**Comment by lexaknyazev** [comment]
Upgraded to .NET 5.0 in #564.
