### ISSUE TITLE
Future Tests

### ISSUE THREAD

**Issue by stevk** [KhronosGroup/glTF-Asset-Generator#69]
These aren't on the roadmap yet

# Positive Tests
- [ ] Max, min values of floats. Only ones with limited ranges? 
- [ ] Texture of different types (normal,opaque) using same texture at the same time
- [ ] Alpha_blend, alpha_mask w/ double sided
- [ ] Alpha modes tested with different alpha factors (1, 0, 0.8)
- [ ] Name field with special cases (null string, duplicated)
- [ ] Support of at least eight morphed attributes
- [ ] jpeg textures
- [ ] Different types of URI (web url, texture in bin, glb)
- [ ] Occlusion, roughness, and metallic textures in both a single packed texture as well as each with its own texture.
- [ ] Node with negative scale and double sided (should work if both features work separately, so low pri).

# Negative Tests
- [ ] Outside of range for attributes that have float values
- [ ] Model missing a top level feature. E.g. Missing material, or node, etc… (Won't render anything)

**Comment by donmccurdy** [comment]
Would like to request a test case using [`accessor.normalized`](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#accessornormalized) as well.

**Comment by bghgary** [comment]
The byte and short accessors here are normalized: https://github.com/bghgary/glTF-Asset-Generator/tree/generated-assets/GeneratedAssets/Primitive_Attribute

We somehow lost the note about this in the README. @stevk @kcoley Can you add this back? Thanks!

**Comment by kcoley** [comment]
I can work on adding the note.  We will also need to push out an update to the generated assets branch since the normalized bytes and shorts were miscomputed in v0.3.  The corrected values are currently available on the develop branch.  I'll work on an update for both of these changes.

**Comment by donmccurdy** [comment]
Awesome, thanks!

**Comment by kcoley** [comment]
No problem!

Here is an updated release with the proper normalized byte and short values and the updated README.  The models have also been changed to the +z forward convention:

https://github.com/bghgary/glTF-Asset-Generator/releases/tag/v0.3.1

**Comment by stevk** [comment]
Consolidated list with #63
